CREATE DATABASE Telecom_Churn;
USE Telecom_Churn;
-- Find total number of customers

SELECT COUNT(*) AS Total_Customers
FROM telecom_churn;

-- Count customers by status

SELECT
    `Customer Status`,
    COUNT(*) AS Customer_Count
FROM telecom_churn
GROUP BY `Customer Status`
ORDER BY Customer_Count DESC;

-- Calculate churn percentage

SELECT
ROUND(
100 * SUM(CASE WHEN `Customer Status`='Churned' THEN 1 ELSE 0 END)
/
COUNT(*),
2
) AS Churn_Rate_Percentage
FROM telecom_churn;

-- Total revenue generated

SELECT
SUM(`Total Revenue`) AS Total_Revenue
FROM telecom_churn;


-- Revenue generated by each customer status

SELECT
    `Customer Status`,
    SUM(`Total Revenue`) AS Revenue
FROM telecom_churn
GROUP BY `Customer Status`
ORDER BY Revenue DESC;


-- Churned customers by gender

SELECT
    Gender,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY Gender
ORDER BY Churned_Customers DESC;


-- Contract types causing highest churn

SELECT
    Contract,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY Contract
ORDER BY Churned_Customers DESC;

-- Internet services with highest churn

SELECT
    `Internet Type`,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY `Internet Type`
ORDER BY Churned_Customers DESC;


-- Payment methods associated with churn

SELECT
    `Payment Method`,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY `Payment Method`
ORDER BY Churned_Customers DESC;


-- Average revenue per customer

SELECT
ROUND(AVG(`Total Revenue`),2) AS Avg_Revenue_Per_Customer
FROM telecom_churn;


-- Cities with highest customer count

SELECT
    City,
    COUNT(*) AS Customers
FROM telecom_churn
GROUP BY City
ORDER BY Customers DESC
LIMIT 10;


-- Cities contributing highest churn

SELECT
    City,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY City
ORDER BY Churned_Customers DESC
LIMIT 10;


-- Compare monthly charges across statuses

SELECT
    `Customer Status`,
    ROUND(AVG(`Monthly Charge`),2) AS Avg_Monthly_Charge
FROM telecom_churn
GROUP BY `Customer Status`;


-- Average tenure by customer status

SELECT
    `Customer Status`,
    ROUND(AVG(`Tenure in Months`),2) AS Avg_Tenure
FROM telecom_churn
GROUP BY `Customer Status`;


-- Main churn categories

SELECT
    `Churn Category`,
    COUNT(*) AS Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY `Churn Category`
ORDER BY Customers DESC;

-- Detailed reasons for customer churn

SELECT
    `Churn Reason`,
    COUNT(*) AS Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY `Churn Reason`
ORDER BY Customers DESC;

-- Churn among customers aged 60+

SELECT
COUNT(*) AS Senior_Churned_Customers
FROM telecom_churn
WHERE Age >= 60
AND `Customer Status`='Churned';


-- Churn comparison by marital status

SELECT
    Married,
    COUNT(*) AS Churned_Customers
FROM telecom_churn
WHERE `Customer Status`='Churned'
GROUP BY Married;

-- Revenue generated by contract types

SELECT
    Contract,
    SUM(`Total Revenue`) AS Revenue
FROM telecom_churn
GROUP BY Contract
ORDER BY Revenue DESC;


-- Executive dashboard KPIs

SELECT

COUNT(*) AS Total_Customers,

SUM(
CASE
WHEN `Customer Status`='Churned'
THEN 1
ELSE 0
END
) AS Churned_Customers,

ROUND(
100 * SUM(
CASE
WHEN `Customer Status`='Churned'
THEN 1
ELSE 0
END
)
/
COUNT(*),
2
) AS Churn_Rate,

SUM(`Total Revenue`) AS Total_Revenue

FROM telecom_churn;











